### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by PeeGey** [droolsassert/droolsassert#1]
Hi man,

I'm using your library and it's working fine, but i have no idea how can i load global variables into drl files. Can you help me with that? Thanks!

**Comment by droolsassert** [comment]
hi!

If I got you right, you should do this in junit @Before method:

    drools.setGlobal("stdout", System.out);

Here is working example [Complex event processing](https://github.com/droolsassert/droolsassert/wiki/2.-Complex-event-processing). If this doesn't answer your question, please be more precise.

Mike

**Comment by droolsassert** [comment]
Resolved

**Comment by PeeGey** [comment]
> hi!
> 
> If I got you right, you should do this in junit @before method:
> 
> ```
> drools.setGlobal("stdout", System.out);
> ```
> 
> Here is working example [Complex event processing](https://github.com/droolsassert/droolsassert/wiki/2.-Complex-event-processing). If this doesn't answer your question, please be more precise.
> 
> Mike

Thanks Mike, that's exactly what i wanted!
