### ISSUE TITLE
Use direct creation of DroolsSession and TestRules without annotations

### ISSUE THREAD

**Issue by ThijmenL98** [droolsassert/droolsassert#11]
I'm trying to write these DroolsAssert tests in Scala with Matchers.
For this, I can unfortunately not use the annotations used in the Java testing code.

Can I somehow create my own DroolsSession and TestRules for these tests?

Currently the code below errors out on a "reassignment to val" on lines `session.resources`, `session.ignoreRules`, `rules.expected` and `rules.ignore`.

```scala
class DroolsTest extends AsyncWordSpec with Matchers {
  private val logger = LoggerFactory.getLogger(classOf[DroolsTest])

  @RegisterExtension val droolsAssert: DroolsAssert = new DroolsAssert()

  var session: DroolsSession = DroolsSessionProxy.newDroolsSessionProxy(new DroolsSessionProxy)
  session.resources = Array("file:src/main/resources/rules/DroolDummy.drl")
  session.ignoreRules = Array("* monitoring")

  "testTemperatureActivationDeactivation" must {
    "succeed" in {
      var proxy = new TestRulesProxy()

      var rules: TestRules = TestRulesProxy.newTestRulesProxy(proxy)
      rules.expected = Array[String](
        "2", "temperature activated",
        "2", "temperature deactivated"
      )
      rules.ignore = Array[String]("throttle *")

      droolsAssert.init(session, rules)
```

**Comment by madamovych** [comment]
hi,

I can check in the evening. Meanwhile could you please create a github repo
to 'checkout, run and reproduce the issue'?
What do you use, maven, gradle? With all dependencies you use, this matters.
Scala should run java code/library without any additional stuff.

You can work with 'provided drools session', here is
<https://github.com/droolsassert/droolsassert/wiki/Spring-integration-test.-Reusing-KieContainer>
an example. Is this sufficient?

Regards
Mike

вт, 13 груд. 2022 р. о 11:23 Thijmen Langendam ***@***.***>
пише:

**Comment by ThijmenL98** [comment]
Unfortunately I cannot provide a quick reproduction repo.
The only thing I'm trying is to run Drools Assertion tests without the need of annotations.

I would like to be able to do e.g.:
```
droolsAssert = new DroolsAssert("somefile.drl")
droolsAssert.insertAndFire(...)
droolsAssert.getRuleFiredAmount("Some rule") == 2
```

**Comment by madamovych** [comment]
There is no simple way to achieve this. Sophisticated sessions creation
with path patterns was one of the main drivers of the library creation. If
you don't need this, stick with 'ordinal way' of creating the session (you
can always encapsulate it inside reusable method). You can check how drools
team write tests.

вт, 13 груд. 2022, 15:21 користувач Thijmen Langendam <
***@***.***> пише:

**Comment by ThijmenL98** [comment]
Could you link "how drools team write tests" for me? I could not find it.

**Comment by madamovych** [comment]
https://github.com/kiegroup/drools/blob/main/drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/regression/DeclarationWithOrTest.java

вт, 13 груд. 2022 р. о 16:17 Thijmen Langendam ***@***.***>
пише:
