### ISSUE TITLE
DroolsAssert not activating rule when date-effective is used

### ISSUE THREAD

**Issue by cjaehnen** [droolsassert/droolsassert#12]
We are leveraging DroolsAssert for isolated tests of Drools rules. We have a requirement to leverage the `date-effective` feature of a rule such that it will only trigger on or after a specific date.

I have a simple Drools rule:

```drools
package app.rule;

import app.model.Policy;

rule "Simple"

enabled true
date-effective "15-Sep-2024"
date-expires "31-Dec-2999"

when
    $policy : Policy(policyNumber == "1234")
then
    $policy.setStateCode("OH");
end
```

I have a POJO called Policy:

```java
package app.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
public class Policy {
    private String policyNumber;
    private String stateCode;
}
```

Here's a test class I'm using verify the rule triggers and the state code is set:

```java
package app;

import app.model.Policy;
import org.droolsassert.DroolsAssert;
import org.droolsassert.DroolsSession;
import org.droolsassert.TestRules;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import static org.assertj.core.api.Assertions.assertThat;

@DroolsSession(resources = "classpath*:/drools/rules/modules/app/Simple.drl", logResources = true)
class SimpleTest {

    @RegisterExtension
    public DroolsAssert drools = new DroolsAssert();

    @Test
    @TestRules(expected = "Simple")
    void testRule() {
        final var policy = Policy.builder()
            .policyNumber("1234")
            .build();

        drools.insertAndFire(policy);

        assertThat(policy.getStateCode()).isEqualTo("OH");
    }
}
```

If I run the test above, the rule fails to activate. Since the current date of this writing is `17-Sep-2024` I would have expected the `date-effective` to activate the rule.

If I comment out this line, and run the same test, the rule activates:

```java
//date-effective "15-Sep-2024"
```

I also ran a test outside of using DroolsAssert and the rule activated with the `date-effective` attribute set.

There appears to be an issue with DroolsAssert not activating rules when `date-effective` is set.

**Comment by madamovych** [comment]
hi Chris,

It's a pity I noticed the issue late.
Could you take a look at [DateEffectiveTest ](https://github.com/droolsassert/droolsassert/blob/master/droolsassert/src/test/java/org/droolsassert/issue/DateEffectiveTest.java)running with v3.3.1 please.
I'm happy to assist OpenGood to serve the greater GOOD for all :)
If you find any issues with the code or face inconveniences with DroolsAssert API, don't hesitate to comment or rise an issue.

Regards,
Mike

**Comment by cjaehnen** [comment]
Hi @madamovych ,

Apologies for the delayed response. I looked at your tests and they looked good!

I tested out the new version and it appears to solve the issue. I'll check the commits for the fix. Always interested what's going on under the hood.

Thanks for assisting OpenGood. Having this library is for the greater good of all developers!

Thanks,
Chris
