### ISSUE TITLE
Ignore multiple rules

### ISSUE THREAD

**Issue by rub3n-san** [droolsassert/droolsassert#2]
Hello,
How can I ignore multiple rules, passing a regex pattern on the ignore of AssertRules?
In your example you have ignore = "* int rule", but what I'm trying to do is to ignore everything after a prefix, like, AAAR2 | abcdef i want to ignore all the rules that start with AAA.

**Comment by droolsassert** [comment]
Hi Jack,

As far as I understood, you need the following:

ignore = { "AAAR2*", "abcdef*" }

You can use regex too, but as for me this would be extra complexity here.
Regex is really undocumented feature, I can't advise better than just browse sources
`org.springframework.util.AntPathMatcher.AntPathStringMatcher.AntPathStringMatcher(String pattern, boolean caseSensitive)`

Mike

**Comment by rub3n-san** [comment]
Hi Mike,

Thank you for the fast response :)

Rule Example: rule "AAAR2 rule description 2"
Rule Example: rule "AAAR3 rule description 3"

When I use ignore = { "AAAR2*", "abcdef*" }, it just ignore that word and does not ignore the whole string ahead.

**Comment by droolsassert** [comment]
Let me confirm, are you trying to suppress execution of rules which starts with AAAR2 or you want to suppress assertion errors related to them?

ignoreRules works with assertActivated and expected = {...}, rules themselves will be executed
if you need to exclude those rules from execution, you need to compose @DroolsSession so that not to load undesired rules.

**Comment by rub3n-san** [comment]
I only want to suppress the assertion. I want to validate chunks of fired rules each time I run a different test.

**Comment by droolsassert** [comment]
will check in few hours

**Comment by droolsassert** [comment]
last stupid question, are you using latest version? I remember some fixes related to that some time ago...

**Comment by rub3n-san** [comment]
Actually not so stupid, I could not import via maven pom, so I downloaded, built and installed myself.  have the 1.7.18 version ... I will try with the 2.0.2.

**Comment by rub3n-san** [comment]
I just updated to 2.0.2, and it's still not working.
Here's a example of a rule:
QRS | R01 | Experiência
QRS | R02 | Produto
QLV | R01 | Utilizacao

and here's what i put on ignore ignore = "QRS*"

**Comment by rub3n-san** [comment]
I think the problem is that come rules descriptions has "/" 
LIKE FOR EXAMPLE:
QTV | R09 | Taxa de crescimento Dívida Líquida / EBITDA - 3

**Comment by rub3n-san** [comment]
I confirmed on my behalf. The problem has "/" on the rules.

**Comment by droolsassert** [comment]
Fixed in 2.0.3. Could you please check whether it works for you?

**Comment by rub3n-san** [comment]
It's working :)
