### ISSUE TITLE
Can't download library from central maven repository

### ISSUE THREAD

**Issue by rub3n-san** [droolsassert/droolsassert#3]
Hi :)

I'm having problems downloading droolsassert from the maven repository i get the following output:
`
Failure to find org.droolsassert:droolsassert-bom:pom:2.0.7 in https://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central-repo has elapsed or updates are forced`

this is what i have on the pom:

  ```
  <dependency>
      <groupId>org.droolsassert</groupId>
      <artifactId>droolsassert</artifactId>
      <version>2.0.7</version>
      <scope>test</scope>
    </dependency>
```
It seems like he's searching for the droolsassert-bom artifact that doesn't exists on the central.

I also tried to add the jar file to my local maven repository and still the same error.

Best regards

**Comment by droolsassert** [comment]
This should be local [cache](https://stackoverflow.com/questions/4856307/when-maven-says-resolution-will-not-be-reattempted-until-the-update-interval-of) issue. Could you try `mvn clean install -U`?

**Comment by droolsassert** [comment]
you are right, looking into it...

**Comment by droolsassert** [comment]
fixed, could you please check if it works for you?

**Comment by rub3n-san** [comment]
I only tested on my personal computer, but it seems to be working! :)

**Comment by droolsassert** [comment]
Thanks a lot for figuring out the problem!
