### ISSUE TITLE
JUnit 5 support?

### ISSUE THREAD

**Issue by roddy** [droolsassert/droolsassert#7]
Are there plans to support JUnit 5 any time soon? 

I'd like to migrate my existing JUnit 5 rules tests to this framework, but I don't use JUnit 4 anymore, and have removed all legacy JUnit support. I can work around the old version of spring, but the JUnit version appears to be a non-starter since most of the legacy `@Rule` support is now gone in favor of the `@ExtendWith` and `@RegisterExtension` annotations.

**Comment by droolsassert** [comment]
Hi Roddy! It will be if somebody care about the feature ;)

**Comment by droolsassert** [comment]
Could you please try 3.0.1?
